# -*- coding: utf-8 -*-
"""EnglishTextToSpeech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11eSlafDJj3aqELQ-QIsaUucfUFo8Yic7
"""

pip install google-cloud-texttospeech

pip install gtts

# اجرای مستقیم در محیط گوگل کُلب
from gtts import gTTS
import os
from IPython.display import Audio, display

# --- تنظیمات ---
a = input("Write a sentences in Eglish to read it :")
text_to_speak = a
audio_file_path = "gtts_persian_output.mp3"
LANGUAGE_CODE = 'en'
# ----------------

def generate_and_play_speech(text, file_path, lang_code):
    """
    تبدیل متن به گفتار، ذخیره در فایل، و پخش فایل در محیط کُلب.
    """
    try:
        # ایجاد فایل صوتی
        tts = gTTS(text=text, lang=lang_code)

        # ذخیره فایل صوتی در حافظه کُلب
        print("در حال تولید فایل صوتی...")
        tts.save(file_path)

        print(f"\n✅ موفقیت‌آمیز بود! فایل صوتی در مسیر زیر ذخیره شد: {file_path}")

        # --- پخش فایل صوتی در محیط کُلب ---
        print("در حال پخش فایل صوتی...")
        display(Audio(file_path, autoplay=True))
        # -----------------------------------

    except Exception as e:
        print("\n❌ خطایی رخ داد:")
        print(f"پیغام خطا: {e}")
        print("لطفاً اتصال اینترنت خود را بررسی کنید.")


if __name__ == "__main__":
    generate_and_play_speech(text_to_speak, audio_file_path, LANGUAGE_CODE)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # Text to Speech in Google Colab
# 
# This project converts English text into speech using gTTS and plays it directly inside Google Colab.
# 
# ## How to Run
# 1. Open Google Colab
# 2. Upload tts_colab.py
# 3. Run the file
# 4. Enter an English sentence
# 
# ## Requirements
# pip install gtts
# 
# ## Author
# Kamyar Naeimi
#